### PR TITLE
Split settings handling from prefs window

### LINKED ISSUE #46: Locking Screen sometimes dock and window list will remain in view
Sometimes when I lock the screen, the dock and window list will be in view.
I am running Gnome 3.14 on EL7.2 Beta with EasyScreenCast 0.97.

(gnome-shell:25649): Gjs-WARNING **: JS ERROR: Exception in callback for signal: updated: Error: Type name EasyScreenCastSettingsWidget is already registered
GObjectMeta<._construct@resource:///org/gnome/gjs/modules/overrides/GObject.js:125
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:204
@/usr/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:329
@/usr/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/convenience.js:34
@/usr/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:36
initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:221
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:110
enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:345
enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:344
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:372
_emit@resource:///org/gnome/gjs/modules/signals.js:124
SessionMode<._sync@resource:///org/gnome/shell/ui/sessionMode.js:205
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
SessionMode<.popMode@resource:///org/gnome/shell/ui/sessionMode.js:174
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
ScreenShield<._continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:1218
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
ScreenShield<.deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:1203
AuthPrompt<.finish@resource:///org/gnome/shell/gdm/authPrompt.js:494
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
UnlockDialog<.finish@resource:///org/gnome/shell/ui/unlockDialog.js:147
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
ScreenShield<.deactivate@resource:///org/gnome/shell/ui/screenShield.js:1202
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
ScreenShield<._init/</<@resource:///org/gnome/shell/ui/screenShield.js:564
_emit@resource:///org/gnome/gjs/modules/signals.js:124
_convertToNativeSignal@resource:///org/gnome/gjs/modules/overrides/Gio.js:129

### PR DESCRIPTION
**Pull request by epozuelo**
To avoid importing and registering the prefs window from the extension,
which breaks gnome-shell when it reloads the extension.

Fixes #46

### CODE REVIEW

**Comment by tobias47n9e** [comment]
Thanks for sending the patch! I will test it immediately.

**Comment by tobias47n9e** [comment]
The patch seems to work really well in the X-session of Fedora 26, but I can't even log into the Wayland session. Still investigating what could cause this issue.

**Comment by epozuelo** [comment]
I assume the Wayland session issue is unrelated to this change, i.e. you can't log in to the Wayland session even without my patch?

Thanks for the prompt review btw!

**Comment by tobias47n9e** [comment]
@epozuelo Indeed the Wayland issues predate your patch. Hopefully someone (or me) has time to look at the Wayland issues soon. Thanks again for the patch. It is really helpful for further development, because now the extension reloads correctly with the Gnome Shell Extension Reloader.

**Comment by epozuelo** [comment]
Cool! By the way what is the Gnome Shell Extension Reloader? Is that an extension? I can't find it, I'd appreciate it if you can point me to it as it sounds useful. Thanks!

**Comment by tobias47n9e** [comment]
It is an extension. Link:
https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader/

**Pull request merged**
