### PR TITLE
Remove sessionMode updated signal in Capture class

### PR DESCRIPTION
**Pull request by meghprkh**
Follows example code from https://gjs.guide/extensions/topics/session-modes.html#example-usage

### CODE REVIEW

**Comment by meghprkh** [comment]
However this is an untested blind change from my side and needs verification from someone who actually understands the code

**Comment by adangel** [comment]
Thanks for the PR and sorry for the late response...

I think, it might be better to remove the code - I don't know why EasyScreenCast is registering a handler when the session mode is changed: The only thing we do here is logging: https://github.com/EasyScreenCast/EasyScreenCast/blob/ae0d1f3d43e54213ae88ab3f147c5fee16e4e1a7/selection.js#L114-L116

We also don't support running while the screen is locked (no parameter "session-modes" in metadata.json ...).

So I see no reason why to call `Main.sessionMode.connect('updated'...` at all.

**Comment by meghprkh** [comment]
Thanks @adangel , updated the PR

**Review by adangel — APPROVED** [review]
Thanks!

**Pull request merged**
